### PR TITLE
Create Higress-Plugin.md

### PR DESCRIPTION
**Pull request by johnlanni**
Fixes: #[Add issue number here]

Changes:

Screenshots of the change:

### CODE REVIEW

**Review by chickenlj — APPROVED** [review]
LGTM.

**Comment by yuluo-yx** [comment]
@johnlanni pls fix ci.

**Comment by johnlanni** [comment]
@yuluo-yx  done

**Review by yuluo-yx — APPROVED** [review]

**Comment by yuluo-yx** [comment]
> @yuluo-yx done

There still seems to be a problem. 🥲

**Comment by johnlanni** [comment]
@yuluo-yx sorry please review again

**Comment by johnlanni** [comment]
@yuluo-yx 😭 please review again, already tested.

**Comment by yuluo-yx** [comment]
> @yuluo-yx 😭 please review again, already tested.

LGTM. 🫡

**Pull request merged**
