### PR TITLE
ci: fix ci

### PR DESCRIPTION
**Pull request by cxhello**

### CODE REVIEW

**Comment by yuluo-yx** [comment]
@cxhello ci looks okay?

**Comment by cxhello** [comment]
@yuluo-yx this is my workflow https://github.com/cxhello/spring-cloud-alibaba-group.github.io/actions/runs/8628060851

**Comment by yuluo-yx** [comment]
> @yuluo-yx this is my workflow https://github.com/cxhello/spring-cloud-alibaba-group.github.io/actions/runs/8628060851 can success.

I mean, ci doesn't seem to be a problem, so why does it need to be fixed?

**Comment by cxhello** [comment]
@yuluo-yx I found that it was successful before because using node.js 18.19. The current failure is using node.js 18.20

https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/actions/runs/8185101529/job/22380764857

https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/actions/runs/8601835648/job/23647245775

**Comment by yuluo-yx** [comment]
> @yuluo-yx发现之前是成功的，因为使用的是node.js 18.19。当前失败是使用node.js 18.20
> 
> https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/actions/runs/8185101529/job/22380764857
> 
> https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/actions/runs/8601835648/job/23647245775

got it.

**Review by yuluo-yx — APPROVED** [review]
LGTM, thanks.

**Comment by cxhello** [comment]
@yuluo-yx  It seems success.

**Comment by yuluo-yx** [comment]
> @yuluo-yx It seems success.

good job 👍

**Comment by cxhello** [comment]
You're welcome

**Pull request merged**
