### PR TITLE
add best practice 

### PR DESCRIPTION
**Pull request by chickenlj**
Documentation for https://github.com/alibaba/spring-cloud-alibaba/pull/3489

### CODE REVIEW

**Comment by yuluo-yx** [comment]
@chickenlj  Pls fix ci.

**Review by yuluo-yx — APPROVED** [review]
LGTM, pls add english version and fix ci. 🫡

**Comment by chickenlj** [comment]
I will fix CI first. And add the english version later with another patch.

**Comment by yuluo-yx** [comment]
> I will fix CI first. And add the english version later with another patch.

got it. 👍

**Pull request merged**
